name: Verify Copyright Headers

on:
  pull_request:
    branches:
      - main

jobs:
  call-verify-copyright:
    uses: SlyFryFrog/toolbox/.github/workflows/verify_copyright.yml@main
    with:
      config: "config.toml"
      directory: "src"
