name: Verify Copyright Headers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-verify-copyright:
    uses: SlyFryFrog/toolbox/.github/workflows/verify_copyright.yml@main
    with:
      author: "Marcus Gigandet"
      directories: "src"
