name: Linux Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, arm64 ]
        include:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
        compiler: [ clang, gcc ]

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update

            sudo apt-get install -y \
              git \
              cmake \
              ninja-build \
              gcc-15 \
              g++-15
          else
            sudo apt-get install -y \
              git \
              cmake \
              ninja-build \
              clang-18 \
              clang-tools-18
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure compiler
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "CC=gcc-15" >> $GITHUB_ENV
            echo "CXX=g++-15" >> $GITHUB_ENV
            echo "PRESET=gcc-release" >> $GITHUB_ENV
          else
            echo "CC=clang-18" >> $GITHUB_ENV
            echo "CXX=clang++-18" >> $GITHUB_ENV
            echo "PRESET=clang-release" >> $GITHUB_ENV
          fi

      - name: Configure CMake
        env:
          CC: ${{ env.CC }}
          CXX: ${{ env.CXX }}
        run: cmake --preset $PRESET -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DMAG_NO_DEV_TOOLS=ON

      - name: Build
        run: cmake --build --preset $PRESET

      - name: Run tests
        run: ctest --preset $PRESET --output-on-failure
