name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check formatting
        uses: marcusgigandet/cmake-tooling/.github/actions/format-lint@4e634975a661ba2f1fe51cc7c5802a507cb688c8
        with:
          globs: |
            :(glob)**/*.h
            :(glob)**/*.hpp
            :(glob)**/*.cppm
            :(glob)**/*.cpp